[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["go mod download", "go build -o queue-processor ."]

[start]
cmd = "CONFIG_FILE=config/mainnet.yaml ./queue-processor"

[variables]
# Update this to the mainnet RPC URL when available
EVM_RPC_URL = "https://galactica-mainnet.example.com"
MERKLE_SERVICE_URL = "grpc-merkle.lookhere.tech:443"
MERKLE_SERVICE_TLS = "true"